services:
  proposal-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: proposal-api
    ports:
      - "5278:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Host=proposal_service_postgres;Port=5432;Database=proposal_service;Username=proposal_service;Password=proposalservice
      - RabbitMq__Host=insurance_platform_rabbit
    networks:
      - insurance_platform_network

networks:
  insurance_platform_network:
    external: true