services:
  contracting-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: contracting-api
    ports:
      - "5292:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Host=contracting_service_postgres;Port=5432;Database=contracting_service;Username=contracting_service;Password=contractingservice
      - RabbitMq__Host=insurance_platform_rabbit
    networks:
      - insurance_platform_network

networks:
  insurance_platform_network:
    external: true